Key: 0 Value: PQcolor
Key: 1 Value: VQcabsize
Key: 3 Value: VQnumberofdoors
Key: 5 Value: PQmaterial
Key: 6 Value: VQbedsize
Key: 7 Value: PQstyle
Key: 8 Value: prodmake
Key: 9 Value: prodmodel
Key: 10 Value: prodsubmodel
Key: 11 Value: prodstartyear
Key: 12 Value: prodendyear
Key: 0 Value: PQcolor
Key: 1 Value: VQcabsize
Key: 3 Value: VQnumberofdoors
Key: 5 Value: PQmaterial
Key: 6 Value: VQbedsize
Key: 7 Value: PQstyle
Key: 8 Value: prodmake
Key: 9 Value: prodmodel
Key: 10 Value: prodsubmodel
Key: 11 Value: prodstartyear
Key: 12 Value: prodendyear
Key: 0 Value: PQcolor
Key: 1 Value: VQcabsize
Key: 3 Value: VQnumberofdoors
Key: 5 Value: PQmaterial
Key: 6 Value: VQbedsize
Key: 7 Value: PQstyle
Key: 8 Value: prodmake
Key: 9 Value: prodmodel
Key: 10 Value: prodsubmodel
Key: 11 Value: prodstartyear
Key: 12 Value: prodendyear
260Key: 0 Value: PQcolor
Key: 1 Value: VQcabsize
Key: 3 Value: VQnumberofdoors
Key: 5 Value: PQmaterial
Key: 6 Value: VQbedsize
Key: 7 Value: PQstyle
Key: 8 Value: prodmake
Key: 9 Value: prodmodel
Key: 10 Value: prodsubmodel
Key: 11 Value: prodstartyear
Key: 12 Value: prodendyear
260Key: 0 Value: PQcolor
Key: 1 Value: VQcabsize
Key: 3 Value: VQnumberofdoors
Key: 5 Value: PQmaterial
Key: 6 Value: VQbedsize
Key: 7 Value: PQstyle
Key: 8 Value: prodmake
Key: 9 Value: prodmodel
Key: 10 Value: prodsubmodel
Key: 11 Value: prodstartyear
Key: 12 Value: prodendyear
260Key: 0 Value: PQcolor
Key: 1 Value: VQcabsize
Key: 3 Value: VQnumberofdoors
Key: 5 Value: PQmaterial
Key: 6 Value: VQbedsize
Key: 7 Value: PQstyle
Key: 8 Value: prodmake
Key: 9 Value: prodmodel
Key: 10 Value: prodsubmodel
Key: 11 Value: prodstartyear
Key: 12 Value: prodendyear
260Key: 0 Value: PQcolor
Key: 1 Value: VQcabsize
Key: 3 Value: VQnumberofdoors
Key: 5 Value: PQmaterial
Key: 6 Value: VQbedsize
Key: 7 Value: PQstyle
Key: 8 Value: prodmake
Key: 9 Value: prodmodel
Key: 10 Value: prodsubmodel
Key: 11 Value: prodstartyear
Key: 12 Value: prodendyear
260Key: 0 Value: PQcolor
Key: 1 Value: VQcabsize
Key: 3 Value: VQnumberofdoors
Key: 5 Value: PQmaterial
Key: 6 Value: VQbedsize
Key: 7 Value: PQstyle
Key: 8 Value: prodmake
Key: 9 Value: prodmodel
Key: 10 Value: prodsubmodel
Key: 11 Value: prodstartyear
Key: 12 Value: prodendyear
260Key: 0 Value: PQcolor
Key: 1 Value: VQcabsize
Key: 3 Value: VQnumberofdoors
Key: 5 Value: PQmaterial
Key: 6 Value: VQbedsize
Key: 7 Value: PQstyle
Key: 8 Value: prodmake
Key: 9 Value: prodmodel
Key: 10 Value: prodsubmodel
Key: 11 Value: prodstartyear
Key: 12 Value: prodendyear
