<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Tue, 28 Feb 2012 20:12:34 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'latest' => 'Unknown',
  'lastCheck' => 1330499554,
);

?>