<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Sun, 26 Jun 2011 22:06:56 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'checkout_authorizenet' => 
  array (
    'requirecvv2' => 'NO',
    'testmode' => 'YES',
    'transactiontype' => 'AUTH_CAPTURE',
    'transactionkey' => '4px54kx6ZZ7489Gq',
    'merchantid' => '7wYB5c6R',
    'displayname' => 'Credit Card',
    'is_setup' => '1',
  ),
  'checkout_googlecheckout' => 
  array (
    'is_setup' => '1',
  ),
);

?>