<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Sun, 26 Feb 2012 23:00:32 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  1 => 
  array (
    'customergroupid' => '1',
    'groupname' => 'eBay - StoreChamp',
    'discount' => '0.0000',
    'discountmethod' => 'price',
    'isdefault' => '0',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
  2 => 
  array (
    'customergroupid' => '2',
    'groupname' => 'eBay - BIA',
    'discount' => '0.0000',
    'discountmethod' => 'price',
    'isdefault' => '0',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
  3 => 
  array (
    'customergroupid' => '3',
    'groupname' => 'eBay – Fastlane',
    'discount' => '0.0000',
    'discountmethod' => 'price',
    'isdefault' => '0',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
  4 => 
  array (
    'customergroupid' => '4',
    'groupname' => 'eBay – Wehaveit',
    'discount' => '0.0000',
    'discountmethod' => 'price',
    'isdefault' => '0',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
  'default' => '5',
  5 => 
  array (
    'customergroupid' => '5',
    'groupname' => 'Truck Champ',
    'discount' => '0.0000',
    'discountmethod' => 'price',
    'isdefault' => '1',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
  6 => 
  array (
    'customergroupid' => '6',
    'groupname' => 'Walk In',
    'discount' => '5.0000',
    'discountmethod' => 'price',
    'isdefault' => '0',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
  7 => 
  array (
    'customergroupid' => '7',
    'groupname' => 'Test - r',
    'discount' => '0.0000',
    'discountmethod' => 'price',
    'isdefault' => '0',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
  8 => 
  array (
    'customergroupid' => '8',
    'groupname' => 'Test - 2',
    'discount' => '7.0000',
    'discountmethod' => 'price',
    'isdefault' => '0',
    'categoryaccesstype' => 'all',
    'accesscategories' => 
    array (
    ),
  ),
);

?>