<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Wed, 29 Feb 2012 14:24:06 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  '' => 
  array (
  ),
  'livechat_liveperson' => 
  array (
    'is_setup' => '1',
  ),
);

?>