<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Fri, 27 May 2011 01:33:53 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  0 => 
  array (
    368 => 
    array (
      'pagetitle' => 'TruckChamp.com - Extang Solid Fold Tonneau Cover - Woodworkers A',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '368',
      'pagecustomersonly' => '0',
    ),
    369 => 
    array (
      'pagetitle' => 'TruckChamp.com - Extang Solid Fold Tonneau Cover - Woodworkers B',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '369',
      'pagecustomersonly' => '0',
    ),
    367 => 
    array (
      'pagetitle' => 'Dealers Special on Ford Nerf/Step Bars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '367',
      'pagecustomersonly' => '0',
    ),
    365 => 
    array (
      'pagetitle' => 'TruckChamp.com Honda Fall Truck Bed Covers Sale - 10% Off!',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '365',
      'pagecustomersonly' => '0',
    ),
    336 => 
    array (
      'pagetitle' => '2010 Harley Davidson Motorcycle Sweepstakes',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '336',
      'pagecustomersonly' => '0',
    ),
    364 => 
    array (
      'pagetitle' => 'TruckChamp.com Chevy Fall Tonneau Sale - 10% Off!',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '364',
      'pagecustomersonly' => '0',
    ),
    363 => 
    array (
      'pagetitle' => 'TruckChamp.com Chevy Fall Truck Bed Covers Sale - 10% Off!',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '363',
      'pagecustomersonly' => '0',
    ),
    361 => 
    array (
      'pagetitle' => 'TruckChamp.com Dodge Fall Tonneau Sale - 10% Off!',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '361',
      'pagecustomersonly' => '0',
    ),
    362 => 
    array (
      'pagetitle' => 'TruckChamp.com Dodge Fall Truck Bed Cover Sale - 10% Off! ',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '362',
      'pagecustomersonly' => '0',
    ),
    358 => 
    array (
      'pagetitle' => 'TruckChamp.com Ford Fall Tonneau Sale - 10% Off!',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '358',
      'pagecustomersonly' => '0',
    ),
    359 => 
    array (
      'pagetitle' => 'TruckChamp.com Ford Fall Truck Bed Covers Sale - 10% Off!',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '359',
      'pagecustomersonly' => '0',
    ),
    357 => 
    array (
      'pagetitle' => 'Overstock Blowout Sale! 10% - 15% off Chevy Silverado Nerf Bars! Only at Truckchamp. Com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '357',
      'pagecustomersonly' => '0',
    ),
    346 => 
    array (
      'pagetitle' => 'Chevy Truck Accessories - Full line of Chevy Truck Accessories at Discounted Prices from Truckchamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '346',
      'pagecustomersonly' => '0',
    ),
    349 => 
    array (
      'pagetitle' => 'Dodge Truck Accessories - Personalize your truck to your specific needs with our discounted prices at TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '349',
      'pagecustomersonly' => '0',
    ),
    345 => 
    array (
      'pagetitle' => 'Ford Truck Accessories - Quality Parts at Discount Prices for your Ford Truck, Auto or SUV',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '345',
      'pagecustomersonly' => '0',
    ),
    350 => 
    array (
      'pagetitle' => 'GMC Truck Accessories – Absolutely everything you need for your GMC at discounted prices from Truckchamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '350',
      'pagecustomersonly' => '0',
    ),
    348 => 
    array (
      'pagetitle' => 'Nissan Truck Accessories - TruckChamp.com has an extensive line of everything for Nissan trucks at discounted prices!',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '348',
      'pagecustomersonly' => '0',
    ),
    347 => 
    array (
      'pagetitle' => 'Toyota Truck Accessories - A complete line of everything Toyota for your truck, auto and SUV',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '347',
      'pagecustomersonly' => '0',
    ),
    337 => 
    array (
      'pagetitle' => 'Overstock Blowout Sale! 10% - 15% off Toyota Tacoma and Tundra Nerf Bars! Only at Truckchamp.com!',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '337',
      'pagecustomersonly' => '0',
    ),
    335 => 
    array (
      'pagetitle' => 'Towing Mirrors - Truck Tow Mirrors',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '335',
      'pagecustomersonly' => '0',
    ),
    316 => 
    array (
      'pagetitle' => 'TruckChamp.com Help Center',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '316',
      'pagecustomersonly' => '0',
    ),
    242 => 
    array (
      'pagetitle' => 'AEM & K&N Fuel Delivery Components - Fuel Filters',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '242',
      'pagecustomersonly' => '0',
    ),
    240 => 
    array (
      'pagetitle' => 'AEM & K&N Fuel Delivery Components - Fuel Pressure Regulator',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '240',
      'pagecustomersonly' => '0',
    ),
    241 => 
    array (
      'pagetitle' => 'AEM & K&N Fuel Delivery Components - Fuel Rails',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '241',
      'pagecustomersonly' => '0',
    ),
    218 => 
    array (
      'pagetitle' => 'AEM Air Intake Systems',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '218',
      'pagecustomersonly' => '0',
    ),
    231 => 
    array (
      'pagetitle' => 'Air Filters and Air Intakes for Trucks, SUVs and Cars, K&N Quality - Air Filter',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '231',
      'pagecustomersonly' => '0',
    ),
    124 => 
    array (
      'pagetitle' => 'Air Filters for Trucks, SUVs and Cars, K&N Quality - Air Filters Basics',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '124',
      'pagecustomersonly' => '0',
    ),
    243 => 
    array (
      'pagetitle' => 'Air Intakes for Trucks, SUVs and Cars, K&N Quality - Air Intakes Basics',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '243',
      'pagecustomersonly' => '0',
    ),
    217 => 
    array (
      'pagetitle' => 'Air Filters and Air Intakes for Trucks, SUVs and Cars, K&N Quality - Air Intake Filter Assembly',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '217',
      'pagecustomersonly' => '0',
    ),
    126 => 
    array (
      'pagetitle' => 'Air Filters and Air Intakes for Trucks, SUVs and Cars, K&N Quality - Benefits of Performance Air Filters',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '126',
      'pagecustomersonly' => '0',
    ),
    128 => 
    array (
      'pagetitle' => 'Air Filters and Air Intakes for Trucks, SUVs and Cars, K&N Quality - Benefits of Performance Air Intakes',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '128',
      'pagecustomersonly' => '0',
    ),
    125 => 
    array (
      'pagetitle' => 'Air Filters and Air Intakes for Trucks, SUVs and Cars, K&N Quality - More About Air Filters',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '125',
      'pagecustomersonly' => '0',
    ),
    127 => 
    array (
      'pagetitle' => 'Air Filters and Air Intakes for Trucks, SUVs and Cars, K&N Quality - More About Air Intakes and Cold Air Intakes',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '127',
      'pagecustomersonly' => '0',
    ),
    193 => 
    array (
      'pagetitle' => 'All Category Photos',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '193',
      'pagecustomersonly' => '0',
    ),
    265 => 
    array (
      'pagetitle' => 'Auto Repair Facts',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '265',
      'pagecustomersonly' => '0',
    ),
    235 => 
    array (
      'pagetitle' => 'Bed Rug: Carpeted Truck Bed Liners - Additional Images',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '235',
      'pagecustomersonly' => '0',
    ),
    234 => 
    array (
      'pagetitle' => 'Bed Rug: Carpeted Truck Bed Liners - Installation',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '234',
      'pagecustomersonly' => '0',
    ),
    279 => 
    array (
      'pagetitle' => 'Billet Grilles / Grille Inserts - Billet Grille Materials',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '279',
      'pagecustomersonly' => '0',
    ),
    278 => 
    array (
      'pagetitle' => 'Billet Grilles / Grille Inserts - Billet Grille Types',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '278',
      'pagecustomersonly' => '0',
    ),
    280 => 
    array (
      'pagetitle' => 'Billet Grilles / Grille Inserts - How To Install A Billet Grille',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '280',
      'pagecustomersonly' => '0',
    ),
    277 => 
    array (
      'pagetitle' => 'Bug Shields, Bug Deflectors and Wind Shields - Hood Protection in Clear, Chrome and Smoke - How Bug Shields / Bug Deflectors Work',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '277',
      'pagecustomersonly' => '0',
    ),
    276 => 
    array (
      'pagetitle' => 'Bug Shields, Bug Deflectors and Wind Shields - Hood Protection in Clear, Chrome and Smoke - Why Bug Shields Are Important',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '276',
      'pagecustomersonly' => '0',
    ),
    304 => 
    array (
      'pagetitle' => 'Bull Bars & Grille Guards - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '304',
      'pagecustomersonly' => '0',
    ),
    305 => 
    array (
      'pagetitle' => 'Bumpers - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '305',
      'pagecustomersonly' => '0',
    ),
    271 => 
    array (
      'pagetitle' => 'Cargo Accessories: Roof Rack, Luggage Rack, Cargo Bag,  Cargo Net, and More! - Cargo Accessories - Loadingzone - **FAQ**',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '271',
      'pagecustomersonly' => '0',
    ),
    67 => 
    array (
      'pagetitle' => 'Chevy / GMC Nerf Bars | Chevy / GMC Step Bars - Quality Discount Chevy / GMC Steps - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '67',
      'pagecustomersonly' => '0',
    ),
    282 => 
    array (
      'pagetitle' => 'Chrome Accessories for Trucks, SUVs, Vans: Mirror Covers, Trim, More - Chrome Accessories Materials',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '282',
      'pagecustomersonly' => '0',
    ),
    284 => 
    array (
      'pagetitle' => 'Chrome Accessories for Trucks, SUVs, Vans: Mirror Covers, Trim, More - Chrome Accessories Trade Shows',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '284',
      'pagecustomersonly' => '0',
    ),
    283 => 
    array (
      'pagetitle' => 'Chrome Accessories for Trucks, SUVs, Vans: Mirror Covers, Trim, More - History of Chrome Accessories.',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '283',
      'pagecustomersonly' => '0',
    ),
    264 => 
    array (
      'pagetitle' => 'Classic Car Shows',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '264',
      'pagecustomersonly' => '0',
    ),
    270 => 
    array (
      'pagetitle' => 'Diesel Power - TruckChamp.com - Truck, Car, & SUV Accessories at the Lowest Prices!',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '270',
      'pagecustomersonly' => '0',
    ),
    296 => 
    array (
      'pagetitle' => 'Discount Nerf Bars - Step Bars from TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '296',
      'pagecustomersonly' => '0',
    ),
    195 => 
    array (
      'pagetitle' => 'Discount Step Bars | Nerf Bars  | Truck Steps:  Your Online Authority - 4 Inch Round Stainless Steel Finish Step Nerf Bars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '195',
      'pagecustomersonly' => '0',
    ),
    197 => 
    array (
      'pagetitle' => 'Discount Step Bars | Nerf Bars  | Truck Steps:  Your Online Authority - Black Oval Step Nerf Bars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '197',
      'pagecustomersonly' => '0',
    ),
    194 => 
    array (
      'pagetitle' => 'Discount Step Bars | Nerf Bars  | Truck Steps:  Your Online Authority - Black Powdercoated Finish Step Nerf Bars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '194',
      'pagecustomersonly' => '0',
    ),
    200 => 
    array (
      'pagetitle' => 'Discount Step Bars | Nerf Bars  | Truck Steps:  Your Online Authority - Nasta (featuring Stainless hardware)',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '200',
      'pagecustomersonly' => '0',
    ),
    196 => 
    array (
      'pagetitle' => 'Discount Step Bars | Nerf Bars  | Truck Steps:  Your Online Authority - Polished Stainless Steel Oval Step Nerf Bars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '196',
      'pagecustomersonly' => '0',
    ),
    123 => 
    array (
      'pagetitle' => 'Discount Step Bars | Nerf Bars  | Truck Steps:  Your Online Authority - Stainless Steel Finish Step Nerf Bars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '123',
      'pagecustomersonly' => '0',
    ),
    199 => 
    array (
      'pagetitle' => 'Discount Step Bars | Nerf Bars  | Truck Steps:  Your Online Authority - Wheel to Wheel Black Powdercoated Finish Step Nerf Bars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '199',
      'pagecustomersonly' => '0',
    ),
    198 => 
    array (
      'pagetitle' => 'Discount Step Bars | Nerf Bars  | Truck Steps:  Your Online Authority - Wheel to Wheel Stainless Steel Step Nerf Bars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '198',
      'pagecustomersonly' => '0',
    ),
    286 => 
    array (
      'pagetitle' => 'Discount Truck Bed Covers - Tonneau Covers2',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '286',
      'pagecustomersonly' => '0',
    ),
    288 => 
    array (
      'pagetitle' => 'Discount Truck Bed Covers - Tonneau Covers3',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '288',
      'pagecustomersonly' => '0',
    ),
    66 => 
    array (
      'pagetitle' => 'Dodge Nerf Bars | Dodge Step Bars - Quality Discount Dodge Steps - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '66',
      'pagecustomersonly' => '0',
    ),
    212 => 
    array (
      'pagetitle' => 'Fender Flares - OriginalRidrZ',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '212',
      'pagecustomersonly' => '0',
    ),
    210 => 
    array (
      'pagetitle' => 'Fender Flares - RuffRidrZ',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '210',
      'pagecustomersonly' => '0',
    ),
    211 => 
    array (
      'pagetitle' => 'Fender Flares - TrailRidrZ',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '211',
      'pagecustomersonly' => '0',
    ),
    65 => 
    array (
      'pagetitle' => 'Ford Nerf Bars | Ford Step Bars - Quality Discount Ford Steps - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '65',
      'pagecustomersonly' => '0',
    ),
    263 => 
    array (
      'pagetitle' => 'Freight Policy',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '263',
      'pagecustomersonly' => '0',
    ),
    267 => 
    array (
      'pagetitle' => 'Headache Rack, BackRack Cab Protection - Headache Rack FAQs',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '267',
      'pagecustomersonly' => '0',
    ),
    251 => 
    array (
      'pagetitle' => 'Headache Rack, BackRack Cab Protection - Headache Rack Installation and Accessories',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '251',
      'pagecustomersonly' => '0',
    ),
    245 => 
    array (
      'pagetitle' => 'Headache Rack, BackRack Cab Protection - Headache Rack Materials',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '245',
      'pagecustomersonly' => '0',
    ),
    266 => 
    array (
      'pagetitle' => 'How To Improve Fuel Economy',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '266',
      'pagecustomersonly' => '0',
    ),
    16 => 
    array (
      'pagetitle' => 'Kate test',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '16',
      'pagecustomersonly' => '0',
    ),
    248 => 
    array (
      'pagetitle' => 'K&N Air Intakes, Air Filters, & Oil Filters - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '248',
      'pagecustomersonly' => '0',
    ),
    307 => 
    array (
      'pagetitle' => 'Lighting For Your Vehicle - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '307',
      'pagecustomersonly' => '0',
    ),
    149 => 
    array (
      'pagetitle' => 'Magnaflow Exhaust Systems',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '149',
      'pagecustomersonly' => '0',
    ),
    215 => 
    array (
      'pagetitle' => 'MBRP Exhaust Systems',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '215',
      'pagecustomersonly' => '0',
    ),
    21 => 
    array (
      'pagetitle' => 'Mounting Nerfs',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '21',
      'pagecustomersonly' => '0',
    ),
    275 => 
    array (
      'pagetitle' => 'Mud Flaps and Mud Guards, Husky Custom Liners  - Materials and Installation For Husky Mud Guards (click to read more!)',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '275',
      'pagecustomersonly' => '0',
    ),
    274 => 
    array (
      'pagetitle' => 'Mud Flaps and Mud Guards, Husky Custom Liners  - Mud Flaps and Mud Guards FAQs (click here to see answers!)',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '274',
      'pagecustomersonly' => '0',
    ),
    273 => 
    array (
      'pagetitle' => 'Mud Flaps and Mud Guards, Husky Custom Liners  - Top Ten Reasons To Purchase Mud Guards / Mud Flaps (click to see our list!)',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '273',
      'pagecustomersonly' => '0',
    ),
    71 => 
    array (
      'pagetitle' => 'Nebraska Nerf Bars | Nebraska Step Bars - Quality Discount Nebraska Steps - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '71',
      'pagecustomersonly' => '0',
    ),
    19 => 
    array (
      'pagetitle' => 'Nerf Bar Materials',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '19',
      'pagecustomersonly' => '0',
    ),
    310 => 
    array (
      'pagetitle' => 'Nerf Bars - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '310',
      'pagecustomersonly' => '0',
    ),
    70 => 
    array (
      'pagetitle' => 'Oklahoma Nerf Bars | Oklahoma Step Bars - Quality Discount Oklahoma Steps - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '70',
      'pagecustomersonly' => '0',
    ),
    314 => 
    array (
      'pagetitle' => 'Overstock Blowout Sale! 10-15% off Dodge Ram Nerf Bars! Only at TruckChamp.com.',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '314',
      'pagecustomersonly' => '0',
    ),
    303 => 
    array (
      'pagetitle' => 'Overstock Blowout Sale! 10-20% off Ford F-150 Nerf Bars! Only at TruckChamp.com.',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '303',
      'pagecustomersonly' => '0',
    ),
    253 => 
    array (
      'pagetitle' => 'privacy & security',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '253',
      'pagecustomersonly' => '0',
    ),
    247 => 
    array (
      'pagetitle' => 'Private Sale for Facebook Users - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '247',
      'pagecustomersonly' => '0',
    ),
    250 => 
    array (
      'pagetitle' => 'Quality Discount Truck Accessories and SUV Accessories -TruckChamp.',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '250',
      'pagecustomersonly' => '0',
    ),
    311 => 
    array (
      'pagetitle' => 'Quality Discount Truck Accessories and SUV Accessories - TruckChamp - 10% Off',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '311',
      'pagecustomersonly' => '0',
    ),
    312 => 
    array (
      'pagetitle' => 'Quality Discount Truck Accessories and SUV Accessories - TruckChamp - 10% Off with Coupon Code',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '312',
      'pagecustomersonly' => '0',
    ),
    33 => 
    array (
      'pagetitle' => 'Resources',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '33',
      'pagecustomersonly' => '0',
    ),
    252 => 
    array (
      'pagetitle' => 'Returns Policy',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '252',
      'pagecustomersonly' => '0',
    ),
    239 => 
    array (
      'pagetitle' => 'Roof Racks & Accessories - HD Series',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '239',
      'pagecustomersonly' => '0',
    ),
    238 => 
    array (
      'pagetitle' => 'Roof Racks & Accessories - Outback Series',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '238',
      'pagecustomersonly' => '0',
    ),
    236 => 
    array (
      'pagetitle' => 'Roof Racks & Accessories - Rack Accessories - Alloy Cargo Tray',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '236',
      'pagecustomersonly' => '0',
    ),
    237 => 
    array (
      'pagetitle' => 'Roof Racks & Accessories - Sport Series',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '237',
      'pagecustomersonly' => '0',
    ),
    1 => 
    array (
      'pagetitle' => 'RSS Syndication',
      'pagetype' => '0',
      'pagelink' => '',
      'pageparentid' => '0',
      'pageid' => '1',
      'pagecustomersonly' => '0',
    ),
    306 => 
    array (
      'pagetitle' => 'Running Boards - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '306',
      'pagecustomersonly' => '0',
    ),
    20 => 
    array (
      'pagetitle' => 'Selecting the Right Nerf Bar',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '20',
      'pagecustomersonly' => '0',
    ),
    18 => 
    array (
      'pagetitle' => 'Shapes and Styles of Nerf Bars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '18',
      'pagecustomersonly' => '0',
    ),
    2 => 
    array (
      'pagetitle' => 'Shipping & Returns',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '2',
      'pagecustomersonly' => '0',
    ),
    255 => 
    array (
      'pagetitle' => 'Shipping Locations',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '255',
      'pagecustomersonly' => '0',
    ),
    254 => 
    array (
      'pagetitle' => 'Shipping Locations Map',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '254',
      'pagecustomersonly' => '0',
    ),
    69 => 
    array (
      'pagetitle' => 'Texas Nerf Bars | Texas Step Bars - Quality Discount Texas Steps - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '69',
      'pagecustomersonly' => '0',
    ),
    285 => 
    array (
      'pagetitle' => 'tonneau test1',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '285',
      'pagecustomersonly' => '0',
    ),
    68 => 
    array (
      'pagetitle' => 'Toyota Nerf Bars | Toyota Step Bars - Quality Discount Toyota Steps - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '68',
      'pagecustomersonly' => '0',
    ),
    308 => 
    array (
      'pagetitle' => 'Truck Bed Accessories - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '308',
      'pagecustomersonly' => '0',
    ),
    25 => 
    array (
      'pagetitle' => 'Truck Bed Mat Customized',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '25',
      'pagecustomersonly' => '0',
    ),
    24 => 
    array (
      'pagetitle' => 'Truck Bed Mat Materials',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '24',
      'pagecustomersonly' => '0',
    ),
    23 => 
    array (
      'pagetitle' => 'Truck Bed Mat Protecting',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '23',
      'pagecustomersonly' => '0',
    ),
    22 => 
    array (
      'pagetitle' => 'Truck Bed Mat Why You Need One',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '22',
      'pagecustomersonly' => '0',
    ),
    272 => 
    array (
      'pagetitle' => 'Truck Bed Rails FAQs',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '272',
      'pagecustomersonly' => '0',
    ),
    158 => 
    array (
      'pagetitle' => 'TruckChamp Installation and Demonstration Videos',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '158',
      'pagecustomersonly' => '0',
    ),
    81 => 
    array (
      'pagetitle' => 'TruckChamp.com - The Only Place for Pick Up Truck Accessories',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '81',
      'pagecustomersonly' => '0',
    ),
    246 => 
    array (
      'pagetitle' => 'TruckChamp.com Launches Newly Redesigned Site',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '246',
      'pagecustomersonly' => '0',
    ),
    317 => 
    array (
      'pagetitle' => 'TruckChamp.com Product Learning Center',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '317',
      'pagecustomersonly' => '0',
    ),
    249 => 
    array (
      'pagetitle' => 'Truckin Magazine - TruckChamp.com - Truck, Car, & SUV Accessories at the Lowest Prices!',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '249',
      'pagecustomersonly' => '0',
    ),
    256 => 
    array (
      'pagetitle' => 'Vehicle by type - Chevy-GMC',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '256',
      'pagecustomersonly' => '0',
    ),
    257 => 
    array (
      'pagetitle' => 'Vehicle by type - Dodge',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '257',
      'pagecustomersonly' => '0',
    ),
    258 => 
    array (
      'pagetitle' => 'Vehicle by type - Ford',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '258',
      'pagecustomersonly' => '0',
    ),
    259 => 
    array (
      'pagetitle' => 'Vehicle by type - GMC',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '259',
      'pagecustomersonly' => '0',
    ),
    260 => 
    array (
      'pagetitle' => 'Vehicle by type - Honda',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '260',
      'pagecustomersonly' => '0',
    ),
    261 => 
    array (
      'pagetitle' => 'Vehicle by type - Nissan',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '261',
      'pagecustomersonly' => '0',
    ),
    262 => 
    array (
      'pagetitle' => 'Vehicle by type - Toyota',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '262',
      'pagecustomersonly' => '0',
    ),
    213 => 
    array (
      'pagetitle' => 'WARN® Winches - Truck & SUV Products - Flares - 4X Fender Flares',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '213',
      'pagecustomersonly' => '0',
    ),
    214 => 
    array (
      'pagetitle' => 'WARN® Winches - Truck & SUV Products - Flares - Trail Flares',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '214',
      'pagecustomersonly' => '0',
    ),
    72 => 
    array (
      'pagetitle' => 'Westin Nerf Bars | Westin Step Bars - Quality Discount Westin Steps - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '72',
      'pagecustomersonly' => '0',
    ),
    17 => 
    array (
      'pagetitle' => 'Why Purchase Nerf Bars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '17',
      'pagecustomersonly' => '0',
    ),
    233 => 
    array (
      'pagetitle' => 'Window Visors, Rain Guards, Vent Visors  - Snap Inz Deflector',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '233',
      'pagecustomersonly' => '0',
    ),
    232 => 
    array (
      'pagetitle' => 'Window Visors, Rain Guards, Vent Visors  - Tape Onz Deflector',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '0',
      'pageid' => '232',
      'pagecustomersonly' => '0',
    ),
  ),
  218 => 
  array (
    220 => 
    array (
      'pagetitle' => 'AEM Air Intake Systems - Brute Force Cold Air Intakes',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '218',
      'pageid' => '220',
      'pagecustomersonly' => '0',
    ),
    222 => 
    array (
      'pagetitle' => 'AEM Air Intake Systems - Brute Force HD Intakes',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '218',
      'pageid' => '222',
      'pagecustomersonly' => '0',
    ),
    219 => 
    array (
      'pagetitle' => 'AEM Air Intake Systems - Cold Air Intake Systems',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '218',
      'pageid' => '219',
      'pagecustomersonly' => '0',
    ),
    229 => 
    array (
      'pagetitle' => 'AEM Air Intake Systems - Hybrid Cold Air Intakes',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '218',
      'pageid' => '229',
      'pagecustomersonly' => '0',
    ),
    225 => 
    array (
      'pagetitle' => 'AEM Air Intake Systems - Short Ram Cold Air Intakes',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '218',
      'pageid' => '225',
      'pagecustomersonly' => '0',
    ),
    227 => 
    array (
      'pagetitle' => 'AEM Air Intake Systems - V2 Intake Systems',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '218',
      'pageid' => '227',
      'pagecustomersonly' => '0',
    ),
  ),
  317 => 
  array (
    318 => 
    array (
      'pagetitle' => 'Air Filters Learning Center',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '317',
      'pageid' => '318',
      'pagecustomersonly' => '0',
    ),
    319 => 
    array (
      'pagetitle' => 'Air Intakes Learning Center',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '317',
      'pageid' => '319',
      'pagecustomersonly' => '0',
    ),
    320 => 
    array (
      'pagetitle' => 'Bed Caps & Bed Rails Learning Center',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '317',
      'pageid' => '320',
      'pagecustomersonly' => '0',
    ),
    321 => 
    array (
      'pagetitle' => 'Bed Mats Learning Center',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '317',
      'pageid' => '321',
      'pagecustomersonly' => '0',
    ),
    322 => 
    array (
      'pagetitle' => 'Bug Shields Learning Center',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '317',
      'pageid' => '322',
      'pagecustomersonly' => '0',
    ),
    323 => 
    array (
      'pagetitle' => 'Chrome Accessories Learning Center',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '317',
      'pageid' => '323',
      'pagecustomersonly' => '0',
    ),
    324 => 
    array (
      'pagetitle' => 'Exhaust Systems Learning Center',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '317',
      'pageid' => '324',
      'pagecustomersonly' => '0',
    ),
    325 => 
    array (
      'pagetitle' => 'Grille Inserts - Billet Grilles Learning Center',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '317',
      'pageid' => '325',
      'pagecustomersonly' => '0',
    ),
    326 => 
    array (
      'pagetitle' => 'Headache Rack Learning Center',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '317',
      'pageid' => '326',
      'pagecustomersonly' => '0',
    ),
    327 => 
    array (
      'pagetitle' => 'Nerf Bars Learning Center',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '317',
      'pageid' => '327',
      'pagecustomersonly' => '0',
    ),
    328 => 
    array (
      'pagetitle' => 'Side View Mirrors Learning Center',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '317',
      'pageid' => '328',
      'pagecustomersonly' => '0',
    ),
    329 => 
    array (
      'pagetitle' => 'Tonneau Covers Learning Center',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '317',
      'pageid' => '329',
      'pagecustomersonly' => '0',
    ),
    330 => 
    array (
      'pagetitle' => 'Towing Mirrors Learning Center',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '317',
      'pageid' => '330',
      'pagecustomersonly' => '0',
    ),
    331 => 
    array (
      'pagetitle' => 'Vent Visors Learning Center',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '317',
      'pageid' => '331',
      'pagecustomersonly' => '0',
    ),
  ),
  314 => 
  array (
    334 => 
    array (
      'pagetitle' => 'Bed Rails - Overstock Blowout Sale! 10-15% off Dodge Ram Nerf Bars! Only at TruckChamp.com.',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '314',
      'pageid' => '334',
      'pagecustomersonly' => '0',
    ),
    333 => 
    array (
      'pagetitle' => 'Bull Bars - Overstock Blowout Sale! 10-15% off Dodge Ram Nerf Bars! Only at TruckChamp.com.',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '314',
      'pageid' => '333',
      'pagecustomersonly' => '0',
    ),
    332 => 
    array (
      'pagetitle' => 'Quad Cab - Overstock Blowout Sale! 10% - 15% off Dodge Ram Nerf Bars! Only at Truckchamp.com!',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '314',
      'pageid' => '332',
      'pagecustomersonly' => '0',
    ),
    315 => 
    array (
      'pagetitle' => 'Regular Cab - Overstock Blowout Sale! 10-15% off Dodge Ram Nerf Bars! Only at TruckChamp.com.',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '314',
      'pageid' => '315',
      'pagecustomersonly' => '0',
    ),
  ),
  303 => 
  array (
    302 => 
    array (
      'pagetitle' => 'Bed Rails - Overstock Blowout Sale! 10-20% off Ford F-150 Nerf Bars! Only at TruckChamp.com.',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '303',
      'pageid' => '302',
      'pagecustomersonly' => '0',
    ),
    301 => 
    array (
      'pagetitle' => 'Bull Bars - Overstock Blowout Sale! 10-20% off Ford F-150 Nerf Bars! Only at TruckChamp.com.',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '303',
      'pageid' => '301',
      'pagecustomersonly' => '0',
    ),
    299 => 
    array (
      'pagetitle' => 'Super Cab - Overstock Blowout Sale! 10-20% off Ford F-150 Nerf Bars! Only at TruckChamp.com.',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '303',
      'pageid' => '299',
      'pagecustomersonly' => '0',
    ),
    300 => 
    array (
      'pagetitle' => 'Super Crew - Overstock Blowout Sale! 10-20% off Ford F-150 Nerf Bars! Only at TruckChamp.com.',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '303',
      'pageid' => '300',
      'pagecustomersonly' => '0',
    ),
    290 => 
    array (
      'pagetitle' => 'Regular Cab - Overstock Blowout Sale! 10-20% off Ford F-150 Nerf Bars! Only at TruckChamp.com.',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '303',
      'pageid' => '290',
      'pagecustomersonly' => '0',
    ),
  ),
  33 => 
  array (
    297 => 
    array (
      'pagetitle' => 'Coupons and Discounts',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '297',
      'pagecustomersonly' => '0',
    ),
    34 => 
    array (
      'pagetitle' => 'Accessories',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '34',
      'pagecustomersonly' => '0',
    ),
    40 => 
    array (
      'pagetitle' => 'ATV Clubs',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '40',
      'pagecustomersonly' => '0',
    ),
    36 => 
    array (
      'pagetitle' => 'Automakers',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '36',
      'pagecustomersonly' => '0',
    ),
    37 => 
    array (
      'pagetitle' => 'Automobile Clubs',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '37',
      'pagecustomersonly' => '0',
    ),
    38 => 
    array (
      'pagetitle' => 'Automobile Directory',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '38',
      'pagecustomersonly' => '0',
    ),
    39 => 
    array (
      'pagetitle' => 'Automobile Forums',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '39',
      'pagecustomersonly' => '0',
    ),
    35 => 
    array (
      'pagetitle' => 'Link Submission',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '35',
      'pagecustomersonly' => '0',
    ),
    289 => 
    array (
      'pagetitle' => 'Miscellaneous Resources',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '289',
      'pagecustomersonly' => '0',
    ),
    41 => 
    array (
      'pagetitle' => 'Parts and Accessories',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '41',
      'pagecustomersonly' => '0',
    ),
    42 => 
    array (
      'pagetitle' => 'RV',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '42',
      'pagecustomersonly' => '0',
    ),
    43 => 
    array (
      'pagetitle' => 'SUV Accessories',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '43',
      'pagecustomersonly' => '0',
    ),
    44 => 
    array (
      'pagetitle' => 'SUV Directory',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '44',
      'pagecustomersonly' => '0',
    ),
    45 => 
    array (
      'pagetitle' => 'SUV Enthusiasts',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '45',
      'pagecustomersonly' => '0',
    ),
    46 => 
    array (
      'pagetitle' => 'SUV Forums',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '46',
      'pagecustomersonly' => '0',
    ),
    47 => 
    array (
      'pagetitle' => 'SUV History',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '47',
      'pagecustomersonly' => '0',
    ),
    48 => 
    array (
      'pagetitle' => 'SUV Manufacturers',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '48',
      'pagecustomersonly' => '0',
    ),
    49 => 
    array (
      'pagetitle' => 'SUV Parts',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '49',
      'pagecustomersonly' => '0',
    ),
    50 => 
    array (
      'pagetitle' => 'SUV Reviews',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '50',
      'pagecustomersonly' => '0',
    ),
    51 => 
    array (
      'pagetitle' => 'SUV Safety',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '51',
      'pagecustomersonly' => '0',
    ),
    52 => 
    array (
      'pagetitle' => 'Tires and Wheels',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '52',
      'pagecustomersonly' => '0',
    ),
    53 => 
    array (
      'pagetitle' => 'Truck Accessories',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '53',
      'pagecustomersonly' => '0',
    ),
    54 => 
    array (
      'pagetitle' => 'Truck Detailing',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '54',
      'pagecustomersonly' => '0',
    ),
    55 => 
    array (
      'pagetitle' => 'Truck Directory',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '55',
      'pagecustomersonly' => '0',
    ),
    56 => 
    array (
      'pagetitle' => 'Truck Enthusiasts',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '56',
      'pagecustomersonly' => '0',
    ),
    57 => 
    array (
      'pagetitle' => 'Truck Forums',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '57',
      'pagecustomersonly' => '0',
    ),
    58 => 
    array (
      'pagetitle' => 'Truck History',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '58',
      'pagecustomersonly' => '0',
    ),
    59 => 
    array (
      'pagetitle' => 'Truck Manufacturers',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '59',
      'pagecustomersonly' => '0',
    ),
    60 => 
    array (
      'pagetitle' => 'Truck Parts',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '60',
      'pagecustomersonly' => '0',
    ),
    61 => 
    array (
      'pagetitle' => 'Truck Restoration',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '61',
      'pagecustomersonly' => '0',
    ),
    63 => 
    array (
      'pagetitle' => 'Truck Safety',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '63',
      'pagecustomersonly' => '0',
    ),
    64 => 
    array (
      'pagetitle' => 'Truck Services',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '33',
      'pageid' => '64',
      'pagecustomersonly' => '0',
    ),
  ),
  337 => 
  array (
    352 => 
    array (
      'pagetitle' => 'CrewMax - Overstock Blowout Sale! 10% - 15% off Toyota  Tundra Nerf Bars! Only at Truckchamp.com!',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '337',
      'pageid' => '352',
      'pagecustomersonly' => '0',
    ),
    351 => 
    array (
      'pagetitle' => 'Access Cab - Overstock Blowout Sale! 10% - 15% off Toyota Tacoma and Tundra Nerf Bars! Only at Truckchamp.com!',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '337',
      'pageid' => '351',
      'pagecustomersonly' => '0',
    ),
    340 => 
    array (
      'pagetitle' => 'Double Cab - Overstock Blowout Sale! 10% - 15% off Toyota Tacoma and Tundra Nerf Bars! Only at Truckchamp.com!',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '337',
      'pageid' => '340',
      'pagecustomersonly' => '0',
    ),
    341 => 
    array (
      'pagetitle' => 'Regular Cab - Overstock Blowout Sale! 10% - 15% off Toyota Tacoma and Tundra Nerf Bars! Only at Truckchamp.com!',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '337',
      'pageid' => '341',
      'pagecustomersonly' => '0',
    ),
    343 => 
    array (
      'pagetitle' => 'Bed Rails - Overstock Blowout Sale! 10% off Toyota Bed Rails! Only at TruckChamp.com.',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '337',
      'pageid' => '343',
      'pagecustomersonly' => '0',
    ),
    342 => 
    array (
      'pagetitle' => 'Bull Bars - Double Cab - Overstock Blowout Sale! 10% - 15% off Toyota Tacoma and Tundra Nerf Bars! Only at Truckchamp.com!',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '337',
      'pageid' => '342',
      'pagecustomersonly' => '0',
    ),
  ),
  149 => 
  array (
    151 => 
    array (
      'pagetitle' => 'Exhaust Systems: Magnaflow Performance - Mario Andretti for Magnaflow',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '151',
      'pagecustomersonly' => '0',
    ),
    163 => 
    array (
      'pagetitle' => 'Exhaust Systems: Magnaflow Performance - Boyd Coddington for Magnaflow',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '163',
      'pagecustomersonly' => '0',
    ),
    162 => 
    array (
      'pagetitle' => 'Exhaust Systems: Magnaflow Performance - Ivan Stewart for Magnaflow',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '162',
      'pagecustomersonly' => '0',
    ),
    164 => 
    array (
      'pagetitle' => 'Exhaust Systems: Magnaflow Performance - Marco Andretti for Magnaflow',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '164',
      'pagecustomersonly' => '0',
    ),
    168 => 
    array (
      'pagetitle' => 'Exhaust Systems: Magnaflow Performance - More Exhaust System Information',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '168',
      'pagecustomersonly' => '0',
    ),
    169 => 
    array (
      'pagetitle' => 'Exhaust Systems: Magnaflow Performance - Stock versus Replacement Exhaust Systems',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '169',
      'pagecustomersonly' => '0',
    ),
    167 => 
    array (
      'pagetitle' => 'Exhaust Systems: Magnaflow Performance - What Is An Exhaust System?',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '167',
      'pagecustomersonly' => '0',
    ),
    156 => 
    array (
      'pagetitle' => 'Magnaflow -  Craig Liebermans BMW M3',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '156',
      'pagecustomersonly' => '0',
    ),
    186 => 
    array (
      'pagetitle' => 'Magnaflow - Chris Hanson\'s 2004 Subaru WRX',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '186',
      'pagecustomersonly' => '0',
    ),
    177 => 
    array (
      'pagetitle' => 'Magnaflow - Corey Longstreth\'s Rat Stylz VR6',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '177',
      'pagecustomersonly' => '0',
    ),
    174 => 
    array (
      'pagetitle' => 'Magnaflow - Customer Testimonials',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '174',
      'pagecustomersonly' => '0',
    ),
    176 => 
    array (
      'pagetitle' => 'Magnaflow - Darron Shubin\'s Nissan 350Z',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '176',
      'pagecustomersonly' => '0',
    ),
    181 => 
    array (
      'pagetitle' => 'Magnaflow - Don Priestley\'s 1967 Chevelle',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '181',
      'pagecustomersonly' => '0',
    ),
    170 => 
    array (
      'pagetitle' => 'Magnaflow - FAQ\'s',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '170',
      'pagecustomersonly' => '0',
    ),
    172 => 
    array (
      'pagetitle' => 'Magnaflow - Install Videos',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '172',
      'pagecustomersonly' => '0',
    ),
    185 => 
    array (
      'pagetitle' => 'Magnaflow - International Allstars Mazda 3',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '185',
      'pagecustomersonly' => '0',
    ),
    188 => 
    array (
      'pagetitle' => 'Magnaflow - Joe Conduff\'s 2000 GMC Sierra 1500',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '188',
      'pagecustomersonly' => '0',
    ),
    183 => 
    array (
      'pagetitle' => 'Magnaflow - Jordan Priestley\'s Speed Racer',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '183',
      'pagecustomersonly' => '0',
    ),
    173 => 
    array (
      'pagetitle' => 'Magnaflow - Lifetime Warranty',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '173',
      'pagecustomersonly' => '0',
    ),
    184 => 
    array (
      'pagetitle' => 'Magnaflow - Louis Ringe\'s Nissan 250Z',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '184',
      'pagecustomersonly' => '0',
    ),
    178 => 
    array (
      'pagetitle' => 'Magnaflow - MagnaFlow Dealers Support Vehicle',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '178',
      'pagecustomersonly' => '0',
    ),
    180 => 
    array (
      'pagetitle' => 'Magnaflow - Neil Tjin\'s Nissan 240SX',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '180',
      'pagecustomersonly' => '0',
    ),
    187 => 
    array (
      'pagetitle' => 'Magnaflow - Neil Tjin\'s Scion TC',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '187',
      'pagecustomersonly' => '0',
    ),
    175 => 
    array (
      'pagetitle' => 'Magnaflow - Show Cars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '175',
      'pagecustomersonly' => '0',
    ),
    161 => 
    array (
      'pagetitle' => 'Magnaflow - Show Cars - Sound Clip',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '161',
      'pagecustomersonly' => '0',
    ),
    166 => 
    array (
      'pagetitle' => 'Magnaflow - Team Drift Alliance',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '149',
      'pageid' => '166',
      'pagecustomersonly' => '0',
    ),
  ),
  357 => 
  array (
    355 => 
    array (
      'pagetitle' => 'Extended Cab - Overstock Blowout Sale! 10% - 15% off Chevy Silverado Nerf Bars! Only at Truckchamp. Com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '357',
      'pageid' => '355',
      'pagecustomersonly' => '0',
    ),
    356 => 
    array (
      'pagetitle' => 'Crew Cab -  Overstock Blowout Sale! 10% - 15% off Chevy Silverado Nerf Bars! Only at Truckchamp. Com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '357',
      'pageid' => '356',
      'pagecustomersonly' => '0',
    ),
    354 => 
    array (
      'pagetitle' => 'Regular Cab - Overstock Blowout Sale! 10% - 15% off Chevy Silverado Nerf Bars! Only at Truckchamp.com!',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '357',
      'pageid' => '354',
      'pagecustomersonly' => '0',
    ),
    353 => 
    array (
      'pagetitle' => 'Towing Mirrors - Overstock Blowout Sale! 10% - 15% off Chevy Silverado Nerf Bars! Only at Truckchamp. Com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '357',
      'pageid' => '353',
      'pagecustomersonly' => '0',
    ),
  ),
  365 => 
  array (
    366 => 
    array (
      'pagetitle' => 'Honda Tonneau Sale - LAST DAY to save 10%',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '365',
      'pageid' => '366',
      'pagecustomersonly' => '0',
    ),
  ),
  336 => 
  array (
    360 => 
    array (
      'pagetitle' => 'Images & Links - TruckChamp.com 2010 Motorcycle Sweepstakes',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '336',
      'pageid' => '360',
      'pagecustomersonly' => '0',
    ),
  ),
  215 => 
  array (
    224 => 
    array (
      'pagetitle' => 'MBRP Performance Exhaust - About Our Systems',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '215',
      'pageid' => '224',
      'pagecustomersonly' => '0',
    ),
    216 => 
    array (
      'pagetitle' => 'MBRP Performance Exhaust - Diesel Exhaust - Chevy',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '215',
      'pageid' => '216',
      'pagecustomersonly' => '0',
    ),
  ),
  310 => 
  array (
    313 => 
    array (
      'pagetitle' => 'Truck Champ 3" Stainless Steel Nerf Bars | Step Bars | Truck Steps',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '310',
      'pageid' => '313',
      'pagecustomersonly' => '0',
    ),
  ),
  72 => 
  array (
    204 => 
    array (
      'pagetitle' => 'Westin - Step Up Products - E-Series Step Bars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '72',
      'pageid' => '204',
      'pagecustomersonly' => '0',
    ),
    209 => 
    array (
      'pagetitle' => 'Westin - Step Up Products - Molded Step Boards',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '72',
      'pageid' => '209',
      'pagecustomersonly' => '0',
    ),
    207 => 
    array (
      'pagetitle' => 'Westin - Step Up Products - Oval Tube 2 Step Bars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '72',
      'pageid' => '207',
      'pagecustomersonly' => '0',
    ),
    206 => 
    array (
      'pagetitle' => 'Westin - Step Up Products - Oval Tube Step Bars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '72',
      'pageid' => '206',
      'pagecustomersonly' => '0',
    ),
    202 => 
    array (
      'pagetitle' => 'Westin - Step Up Products - Platinum Series Step Bars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '72',
      'pageid' => '202',
      'pagecustomersonly' => '0',
    ),
    203 => 
    array (
      'pagetitle' => 'Westin - Step Up Products - Signature Series',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '72',
      'pageid' => '203',
      'pagecustomersonly' => '0',
    ),
    201 => 
    array (
      'pagetitle' => 'Westin - Step Up Products - Sport Tube Side Bars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '72',
      'pageid' => '201',
      'pagecustomersonly' => '0',
    ),
    208 => 
    array (
      'pagetitle' => 'Westin - Step Up Products - Sure Grip Running Boards',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '72',
      'pageid' => '208',
      'pagecustomersonly' => '0',
    ),
    205 => 
    array (
      'pagetitle' => 'Westin - Step Up Products - Wheel-to-Wheel Step Bars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '72',
      'pageid' => '205',
      'pagecustomersonly' => '0',
    ),
    80 => 
    array (
      'pagetitle' => 'Westin - Step Up Products',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '72',
      'pageid' => '80',
      'pagecustomersonly' => '0',
    ),
  ),
  81 => 
  array (
    189 => 
    array (
      'pagetitle' => 'History of Truck Accessories',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '189',
      'pagecustomersonly' => '0',
    ),
    192 => 
    array (
      'pagetitle' => 'Top 10 Things NOT To Do With Your Nerf Bars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '192',
      'pagecustomersonly' => '0',
    ),
    191 => 
    array (
      'pagetitle' => 'Top 10 Things NOT To Do With Your Tonneau Cover',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '191',
      'pagecustomersonly' => '0',
    ),
    157 => 
    array (
      'pagetitle' => 'Carpet and bed rails for your truck',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '157',
      'pagecustomersonly' => '0',
    ),
    154 => 
    array (
      'pagetitle' => 'Does Owning a Truck Make You a Redneck? - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '154',
      'pagecustomersonly' => '0',
    ),
    159 => 
    array (
      'pagetitle' => 'Ford step bars and accessories',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '159',
      'pagecustomersonly' => '0',
    ),
    155 => 
    array (
      'pagetitle' => 'Testimonial - Roger\'s Truck - TruckChamp®',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '155',
      'pagecustomersonly' => '0',
    ),
    165 => 
    array (
      'pagetitle' => 'Top 5 TV Cars and Trucks - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '165',
      'pagecustomersonly' => '0',
    ),
    160 => 
    array (
      'pagetitle' => 'Tube steps and other step bars for Ford trucks',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '160',
      'pagecustomersonly' => '0',
    ),
    171 => 
    array (
      'pagetitle' => 'Ultimate Offroad Vehicles - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '171',
      'pagecustomersonly' => '0',
    ),
    179 => 
    array (
      'pagetitle' => 'Understanding Car Care from TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '179',
      'pagecustomersonly' => '0',
    ),
    182 => 
    array (
      'pagetitle' => 'Unique Truck Equipment from TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '182',
      'pagecustomersonly' => '0',
    ),
    104 => 
    array (
      'pagetitle' => '60 Iconic and Classic Cars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '104',
      'pagecustomersonly' => '0',
    ),
    137 => 
    array (
      'pagetitle' => 'Auto Repair 101 from TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '137',
      'pagecustomersonly' => '0',
    ),
    153 => 
    array (
      'pagetitle' => 'Best, Worst and Strangest Police Cars',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '153',
      'pagecustomersonly' => '0',
    ),
    138 => 
    array (
      'pagetitle' => 'Billet grilles and truck bed carpet for your automobile - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '138',
      'pagecustomersonly' => '0',
    ),
    82 => 
    array (
      'pagetitle' => 'Buy discount pick up truck accessories online',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '82',
      'pagecustomersonly' => '0',
    ),
    90 => 
    array (
      'pagetitle' => 'Chevrolet Truck Accessories and More from TruckChamp®',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '90',
      'pagecustomersonly' => '0',
    ),
    144 => 
    array (
      'pagetitle' => 'Buy Ford and Chevrolet Accessories Online from TruckChamp®',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '144',
      'pagecustomersonly' => '0',
    ),
    150 => 
    array (
      'pagetitle' => 'Can Hybrid Cars, Trucks, and SUVs Break Into The Mainstream?',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '150',
      'pagecustomersonly' => '0',
    ),
    140 => 
    array (
      'pagetitle' => 'Celebrity Trucks and Celebrity SUV\'s - Top 7 Celebrity Trucks from TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '140',
      'pagecustomersonly' => '0',
    ),
    141 => 
    array (
      'pagetitle' => 'Chevy Truck and Other Dependable Pickup Truck Accessories from TruckChamp®',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '141',
      'pagecustomersonly' => '0',
    ),
    142 => 
    array (
      'pagetitle' => 'Deep Cycle Batteries from TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '142',
      'pagecustomersonly' => '0',
    ),
    83 => 
    array (
      'pagetitle' => 'Discount pickup truck accessories',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '83',
      'pagecustomersonly' => '0',
    ),
    143 => 
    array (
      'pagetitle' => 'Discount Trailer Hitches, Nerf Bars&trade;, and Pickup Accessories from TruckChamp®',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '143',
      'pagecustomersonly' => '0',
    ),
    145 => 
    array (
      'pagetitle' => 'Ford and Dodge Truck Accessories Everyone Will Love - TruckChamp®',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '145',
      'pagecustomersonly' => '0',
    ),
    105 => 
    array (
      'pagetitle' => 'Guide to Alternative Fuels from TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '105',
      'pagecustomersonly' => '0',
    ),
    148 => 
    array (
      'pagetitle' => 'Hottest 5 Trucks and SUVs for 2008',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '148',
      'pagecustomersonly' => '0',
    ),
    146 => 
    array (
      'pagetitle' => 'Stylish Grill and Brush Guards',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '146',
      'pagecustomersonly' => '0',
    ),
    152 => 
    array (
      'pagetitle' => 'Top 13 Monster Truck Crashes - TruckChamp.com',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '152',
      'pagecustomersonly' => '0',
    ),
    139 => 
    array (
      'pagetitle' => 'Top 9 Cars and Trucks - in Videogames',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '139',
      'pagecustomersonly' => '0',
    ),
    147 => 
    array (
      'pagetitle' => 'What You Need to Know Before Buying a Trailer Hitch',
      'pagetype' => '0',
      'pagelink' => 'http://',
      'pageparentid' => '81',
      'pageid' => '147',
      'pagecustomersonly' => '0',
    ),
  ),
  'defaultPage' => false,
);

?>