<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Mon, 20 Feb 2012 21:49:45 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  0 => 
  array (
    677 => 
    array (
      'categoryid' => '677',
      'catparentid' => '0',
      'catname' => 'Catalytic Converters',
    ),
    813 => 
    array (
      'categoryid' => '813',
      'catparentid' => '0',
      'catname' => 'Test category - r',
    ),
    786 => 
    array (
      'categoryid' => '786',
      'catparentid' => '0',
      'catname' => 'Engine Dress Up',
    ),
    793 => 
    array (
      'categoryid' => '793',
      'catparentid' => '0',
      'catname' => 'Jeep Items',
    ),
    128 => 
    array (
      'categoryid' => '128',
      'catparentid' => '0',
      'catname' => 'Brake Controllers',
    ),
    268 => 
    array (
      'categoryid' => '268',
      'catparentid' => '0',
      'catname' => 'Exhaust Systems',
    ),
    758 => 
    array (
      'categoryid' => '758',
      'catparentid' => '0',
      'catname' => 'Towing Mirrors',
    ),
    15 => 
    array (
      'categoryid' => '15',
      'catparentid' => '0',
      'catname' => 'Air Filter',
    ),
    446 => 
    array (
      'categoryid' => '446',
      'catparentid' => '0',
      'catname' => 'Hot Rod Exhaust Kit',
    ),
    763 => 
    array (
      'categoryid' => '763',
      'catparentid' => '0',
      'catname' => 'Wheel Simulators',
    ),
    16 => 
    array (
      'categoryid' => '16',
      'catparentid' => '0',
      'catname' => 'Air Intakes',
    ),
    63 => 
    array (
      'categoryid' => '63',
      'catparentid' => '0',
      'catname' => 'Bed Caps & Bed Rails',
    ),
    229 => 
    array (
      'categoryid' => '229',
      'catparentid' => '0',
      'catname' => 'Catalytic Converter-49 State',
    ),
    27 => 
    array (
      'categoryid' => '27',
      'catparentid' => '0',
      'catname' => 'Cam Gears',
    ),
    232 => 
    array (
      'categoryid' => '232',
      'catparentid' => '0',
      'catname' => 'Catalytic Converter-California',
    ),
    161 => 
    array (
      'categoryid' => '161',
      'catparentid' => '0',
      'catname' => 'Fifth Wheels',
    ),
    319 => 
    array (
      'categoryid' => '319',
      'catparentid' => '0',
      'catname' => 'Roof Racks',
    ),
    633 => 
    array (
      'categoryid' => '633',
      'catparentid' => '0',
      'catname' => 'Bed Liners',
    ),
    28 => 
    array (
      'categoryid' => '28',
      'catparentid' => '0',
      'catname' => 'Cooling',
    ),
    68 => 
    array (
      'categoryid' => '68',
      'catparentid' => '0',
      'catname' => 'Bed Mats',
    ),
    17 => 
    array (
      'categoryid' => '17',
      'catparentid' => '0',
      'catname' => 'Fuel Delivery',
    ),
    127 => 
    array (
      'categoryid' => '127',
      'catparentid' => '0',
      'catname' => 'Bike Carrier',
    ),
    238 => 
    array (
      'categoryid' => '238',
      'catparentid' => '0',
      'catname' => 'Exhaust Tips',
    ),
    385 => 
    array (
      'categoryid' => '385',
      'catparentid' => '0',
      'catname' => 'Ignition',
    ),
    20 => 
    array (
      'categoryid' => '20',
      'catparentid' => '0',
      'catname' => 'BedSlide',
    ),
    224 => 
    array (
      'categoryid' => '224',
      'catparentid' => '0',
      'catname' => 'Mufflers',
    ),
    19 => 
    array (
      'categoryid' => '19',
      'catparentid' => '0',
      'catname' => 'Oil Filters',
    ),
    72 => 
    array (
      'categoryid' => '72',
      'catparentid' => '0',
      'catname' => 'Bug Shields - Bug Deflectors',
    ),
    31 => 
    array (
      'categoryid' => '31',
      'catparentid' => '0',
      'catname' => 'Performance Chips',
    ),
    76 => 
    array (
      'categoryid' => '76',
      'catparentid' => '0',
      'catname' => 'Bull Bars & Grille Guards',
    ),
    322 => 
    array (
      'categoryid' => '322',
      'catparentid' => '0',
      'catname' => 'Bumpers',
    ),
    315 => 
    array (
      'categoryid' => '315',
      'catparentid' => '0',
      'catname' => 'Cargo Accessories',
    ),
    167 => 
    array (
      'categoryid' => '167',
      'catparentid' => '0',
      'catname' => 'GooseNeck - Fifth Wheel Hitches',
    ),
    290 => 
    array (
      'categoryid' => '290',
      'catparentid' => '0',
      'catname' => 'Chrome Accessories',
    ),
    673 => 
    array (
      'categoryid' => '673',
      'catparentid' => '0',
      'catname' => 'Construction - Ladder Racks',
    ),
    175 => 
    array (
      'categoryid' => '175',
      'catparentid' => '0',
      'catname' => 'Hitches',
    ),
    393 => 
    array (
      'categoryid' => '393',
      'catparentid' => '0',
      'catname' => 'Decals',
    ),
    26 => 
    array (
      'categoryid' => '26',
      'catparentid' => '0',
      'catname' => 'Du-Ha Underseat Storage',
    ),
    79 => 
    array (
      'categoryid' => '79',
      'catparentid' => '0',
      'catname' => 'Fender Flares - Fender Trim',
    ),
    104 => 
    array (
      'categoryid' => '104',
      'catparentid' => '0',
      'catname' => 'Floor Mats - Floor Liners',
    ),
    295 => 
    array (
      'categoryid' => '295',
      'catparentid' => '0',
      'catname' => 'Gauges',
    ),
    83 => 
    array (
      'categoryid' => '83',
      'catparentid' => '0',
      'catname' => 'Grille Inserts - Billet Grilles',
    ),
    634 => 
    array (
      'categoryid' => '634',
      'catparentid' => '0',
      'catname' => 'Headache Racks',
    ),
    282 => 
    array (
      'categoryid' => '282',
      'catparentid' => '0',
      'catname' => 'Headlight / Taillight Cover',
    ),
    377 => 
    array (
      'categoryid' => '377',
      'catparentid' => '0',
      'catname' => 'Hood Scoops',
    ),
    397 => 
    array (
      'categoryid' => '397',
      'catparentid' => '0',
      'catname' => 'License Plates',
    ),
    330 => 
    array (
      'categoryid' => '330',
      'catparentid' => '0',
      'catname' => 'Lighting',
    ),
    86 => 
    array (
      'categoryid' => '86',
      'catparentid' => '0',
      'catname' => 'Mud Flaps - Mud Guards',
    ),
    57 => 
    array (
      'categoryid' => '57',
      'catparentid' => '0',
      'catname' => 'Nerf Bars',
    ),
    338 => 
    array (
      'categoryid' => '338',
      'catparentid' => '0',
      'catname' => 'Plows',
    ),
    325 => 
    array (
      'categoryid' => '325',
      'catparentid' => '0',
      'catname' => 'Running Boards',
    ),
    756 => 
    array (
      'categoryid' => '756',
      'catparentid' => '0',
      'catname' => 'Side View Mirrors',
    ),
    328 => 
    array (
      'categoryid' => '328',
      'catparentid' => '0',
      'catname' => 'Tail Light Guard',
    ),
    4 => 
    array (
      'categoryid' => '4',
      'catparentid' => '0',
      'catname' => 'Tonneau Covers',
    ),
    1 => 
    array (
      'categoryid' => '1',
      'catparentid' => '0',
      'catname' => 'Truck Bed Accessories',
    ),
    25 => 
    array (
      'categoryid' => '25',
      'catparentid' => '0',
      'catname' => 'Truck Bed Tailgate Extension',
    ),
    729 => 
    array (
      'categoryid' => '729',
      'catparentid' => '0',
      'catname' => 'Truck Racks & Van Racks',
    ),
    101 => 
    array (
      'categoryid' => '101',
      'catparentid' => '0',
      'catname' => 'Vent Visors',
    ),
    120 => 
    array (
      'categoryid' => '120',
      'catparentid' => '0',
      'catname' => 'Suspension Kits and Air Suspension',
    ),
    112 => 
    array (
      'categoryid' => '112',
      'catparentid' => '0',
      'catname' => 'Fog Lights',
    ),
    340 => 
    array (
      'categoryid' => '340',
      'catparentid' => '0',
      'catname' => 'Light Covers',
    ),
    342 => 
    array (
      'categoryid' => '342',
      'catparentid' => '0',
      'catname' => 'Spot Light',
    ),
    113 => 
    array (
      'categoryid' => '113',
      'catparentid' => '0',
      'catname' => 'Trailer Lights',
    ),
    114 => 
    array (
      'categoryid' => '114',
      'catparentid' => '0',
      'catname' => 'Stock Replacement',
    ),
    117 => 
    array (
      'categoryid' => '117',
      'catparentid' => '0',
      'catname' => 'Towing',
    ),
    124 => 
    array (
      'categoryid' => '124',
      'catparentid' => '0',
      'catname' => 'Body Lifts',
    ),
    125 => 
    array (
      'categoryid' => '125',
      'catparentid' => '0',
      'catname' => 'Lifting',
    ),
    126 => 
    array (
      'categoryid' => '126',
      'catparentid' => '0',
      'catname' => 'Lowering',
    ),
    214 => 
    array (
      'categoryid' => '214',
      'catparentid' => '0',
      'catname' => 'Atv Winch',
    ),
    210 => 
    array (
      'categoryid' => '210',
      'catparentid' => '0',
      'catname' => 'Hubs',
    ),
    215 => 
    array (
      'categoryid' => '215',
      'catparentid' => '0',
      'catname' => 'Winch',
    ),
    221 => 
    array (
      'categoryid' => '221',
      'catparentid' => '0',
      'catname' => 'Winch Mount',
    ),
  ),
);

?>