<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Thu, 12 Nov 2009 05:20:07 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  '' => 
  array (
  ),
);

?>