<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Thu, 26 May 2011 23:18:39 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  1 => 
  array (
    'currencyid' => '1',
    'currencycountryid' => '226',
    'currencycouregid' => NULL,
    'currencycode' => 'USD',
    'currencyconvertercode' => NULL,
    'currencyname' => 'Default Currency',
    'currencyexchangerate' => '1.0000000000',
    'currencystring' => '$',
    'currencystringposition' => 'left',
    'currencydecimalstring' => '.',
    'currencythousandstring' => ',',
    'currencydecimalplace' => '2',
    'currencylastupdated' => '1241808637',
    'currencyisdefault' => '1',
    'currencystatus' => '1',
  ),
  'default' => '1',
);

?>