<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Thu, 26 May 2011 23:18:39 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  'analytics_googleanalytics' => 
  array (
    'is_setup' => '1',
    'trackingcode' => '<script type="text/javascript">
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write(unescape("%3Cscript src=\'" + gaJsHost + "google-analytics.com/ga.js\' type=\'text/javascript\'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
try {
var pageTracker = _gat._getTracker("UA-213948-1");
pageTracker._trackPageview();
} catch(err) {}</script>',
  ),
);

?>