<?php

/** Interspire Shopping Cart Data Store File **
  *
  * Generated: Sun, 19 Feb 2012 20:38:13 +0000
  *
  * DO NOT EDIT THIS FILE MANUALLY
  *
*/

$cacheData = array (
  1 => 
  array (
    'vendorid' => '1',
    'vendorname' => 'Westin',
    'vendorfriendlyname' => 'westin',
    'vendorshipping' => '0',
  ),
  2 => 
  array (
    'vendorid' => '2',
    'vendorname' => 'Extang',
    'vendorfriendlyname' => 'extang',
    'vendorshipping' => '0',
  ),
  3 => 
  array (
    'vendorid' => '3',
    'vendorname' => 'K&N',
    'vendorfriendlyname' => 'kn',
    'vendorshipping' => '0',
  ),
  4 => 
  array (
    'vendorid' => '4',
    'vendorname' => 'Truck Champ',
    'vendorfriendlyname' => 'truck-champ',
    'vendorshipping' => '0',
  ),
  5 => 
  array (
    'vendorid' => '5',
    'vendorname' => 'Magnaflow',
    'vendorfriendlyname' => 'magnaflow',
    'vendorshipping' => '0',
  ),
  6 => 
  array (
    'vendorid' => '6',
    'vendorname' => 'Advantage',
    'vendorfriendlyname' => 'advantage',
    'vendorshipping' => '0',
  ),
  7 => 
  array (
    'vendorid' => '7',
    'vendorname' => 'Truxedo',
    'vendorfriendlyname' => 'truxedo',
    'vendorshipping' => '0',
  ),
  8 => 
  array (
    'vendorid' => '8',
    'vendorname' => 'BakFlip',
    'vendorfriendlyname' => 'bakflip',
    'vendorshipping' => '0',
  ),
  9 => 
  array (
    'vendorid' => '9',
    'vendorname' => 'Backrack',
    'vendorfriendlyname' => 'backrack',
    'vendorshipping' => '0',
  ),
  10 => 
  array (
    'vendorid' => '10',
    'vendorname' => 'Bedrug',
    'vendorfriendlyname' => 'bedrug',
    'vendorshipping' => '0',
  ),
  11 => 
  array (
    'vendorid' => '11',
    'vendorname' => 'Husky',
    'vendorfriendlyname' => 'husky',
    'vendorshipping' => '0',
  ),
  12 => 
  array (
    'vendorid' => '12',
    'vendorname' => 'Stampede',
    'vendorfriendlyname' => 'stampede',
    'vendorshipping' => '0',
  ),
  14 => 
  array (
    'vendorid' => '14',
    'vendorname' => 'MBRP',
    'vendorfriendlyname' => 'mbrp',
    'vendorshipping' => '0',
  ),
  15 => 
  array (
    'vendorid' => '15',
    'vendorname' => 'Du-Ha',
    'vendorfriendlyname' => 'du-ha',
    'vendorshipping' => '0',
  ),
  16 => 
  array (
    'vendorid' => '16',
    'vendorname' => 'AEM',
    'vendorfriendlyname' => 'aem',
    'vendorshipping' => '0',
  ),
  17 => 
  array (
    'vendorid' => '17',
    'vendorname' => 'Warn',
    'vendorfriendlyname' => 'warn',
    'vendorshipping' => '0',
  ),
  18 => 
  array (
    'vendorid' => '18',
    'vendorname' => 'Edge',
    'vendorfriendlyname' => 'edge',
    'vendorshipping' => '0',
  ),
  19 => 
  array (
    'vendorid' => '19',
    'vendorname' => 'Firestone',
    'vendorfriendlyname' => 'firestone',
    'vendorshipping' => '0',
  ),
  20 => 
  array (
    'vendorid' => '20',
    'vendorname' => 'LRV',
    'vendorfriendlyname' => 'lrv',
    'vendorshipping' => '0',
  ),
  21 => 
  array (
    'vendorid' => '21',
    'vendorname' => 'EZLoad',
    'vendorfriendlyname' => 'ezload',
    'vendorshipping' => '0',
  ),
  22 => 
  array (
    'vendorid' => '22',
    'vendorname' => 'Airaid',
    'vendorfriendlyname' => 'airaid',
    'vendorshipping' => '0',
  ),
  23 => 
  array (
    'vendorid' => '23',
    'vendorname' => 'Pop N Lock',
    'vendorfriendlyname' => 'pop-n-lock',
    'vendorshipping' => '0',
  ),
  24 => 
  array (
    'vendorid' => '24',
    'vendorname' => 'Hypertech',
    'vendorfriendlyname' => 'hypertech',
    'vendorshipping' => '0',
  ),
  25 => 
  array (
    'vendorid' => '25',
    'vendorname' => 'Undercover',
    'vendorfriendlyname' => 'undercover',
    'vendorshipping' => '0',
  ),
  26 => 
  array (
    'vendorid' => '26',
    'vendorname' => 'Nifty',
    'vendorfriendlyname' => 'nifty',
    'vendorshipping' => '0',
  ),
  27 => 
  array (
    'vendorid' => '27',
    'vendorname' => 'Curt',
    'vendorfriendlyname' => 'curt',
    'vendorshipping' => '0',
  ),
  28 => 
  array (
    'vendorid' => '28',
    'vendorname' => 'MacNeil',
    'vendorfriendlyname' => 'macneil',
    'vendorshipping' => '0',
  ),
  29 => 
  array (
    'vendorid' => '29',
    'vendorname' => 'Agricover',
    'vendorfriendlyname' => 'agricover',
    'vendorshipping' => '0',
  ),
  30 => 
  array (
    'vendorid' => '30',
    'vendorname' => 'CongoWorld',
    'vendorfriendlyname' => 'congoworld-packages',
    'vendorshipping' => '0',
  ),
  49 => 
  array (
    'vendorid' => '49',
    'vendorname' => 'TonnoPro',
    'vendorfriendlyname' => 'tonnopro',
    'vendorshipping' => '0',
  ),
  50 => 
  array (
    'vendorid' => '50',
    'vendorname' => 'Lund',
    'vendorfriendlyname' => 'lund',
    'vendorshipping' => '0',
  ),
  51 => 
  array (
    'vendorid' => '51',
    'vendorname' => 'Cargo Buckle',
    'vendorfriendlyname' => 'cargo-buckle',
    'vendorshipping' => '0',
  ),
  52 => 
  array (
    'vendorid' => '52',
    'vendorname' => 'LoadHandler',
    'vendorfriendlyname' => 'loadhandler',
    'vendorshipping' => '0',
  ),
  53 => 
  array (
    'vendorid' => '53',
    'vendorname' => 'Loading Zone',
    'vendorfriendlyname' => 'loading-zone',
    'vendorshipping' => '0',
  ),
  54 => 
  array (
    'vendorid' => '54',
    'vendorname' => 'DiabloSport',
    'vendorfriendlyname' => 'diablo',
    'vendorshipping' => '0',
  ),
  55 => 
  array (
    'vendorid' => '55',
    'vendorname' => 'Univ',
    'vendorfriendlyname' => 'univ',
    'vendorshipping' => '0',
  ),
  56 => 
  array (
    'vendorid' => '56',
    'vendorname' => 'Discount Tonneaus',
    'vendorfriendlyname' => 'discount-tonneaus',
    'vendorshipping' => '0',
  ),
  57 => 
  array (
    'vendorid' => '57',
    'vendorname' => 'Hidden Hitch',
    'vendorfriendlyname' => 'hidden-hitch',
    'vendorshipping' => '0',
  ),
  58 => 
  array (
    'vendorid' => '58',
    'vendorname' => 'G2 USA',
    'vendorfriendlyname' => '',
    'vendorshipping' => '0',
  ),
  59 => 
  array (
    'vendorid' => '59',
    'vendorname' => 'NI Brand',
    'vendorfriendlyname' => '',
    'vendorshipping' => '0',
  ),
  60 => 
  array (
    'vendorid' => '60',
    'vendorname' => 'T-Rex',
    'vendorfriendlyname' => 't-rex',
    'vendorshipping' => '0',
  ),
  61 => 
  array (
    'vendorid' => '61',
    'vendorname' => 'PIAA',
    'vendorfriendlyname' => 'piaa',
    'vendorshipping' => '0',
  ),
  62 => 
  array (
    'vendorid' => '62',
    'vendorname' => 'BestInAuto',
    'vendorfriendlyname' => 'bestinauto',
    'vendorshipping' => '0',
  ),
  63 => 
  array (
    'vendorid' => '63',
    'vendorname' => 'Cipa',
    'vendorfriendlyname' => 'cipa',
    'vendorshipping' => '0',
  ),
  64 => 
  array (
    'vendorid' => '64',
    'vendorname' => 'BestInAUTO',
    'vendorfriendlyname' => 'all-sales',
    'vendorshipping' => '0',
  ),
  65 => 
  array (
    'vendorid' => '65',
    'vendorname' => 'Rugged Ridge',
    'vendorfriendlyname' => '',
    'vendorshipping' => '0',
  ),
  66 => 
  array (
    'vendorid' => '66',
    'vendorname' => 'Superchips',
    'vendorfriendlyname' => 'superchips',
    'vendorshipping' => '0',
  ),
  67 => 
  array (
    'vendorid' => '67',
    'vendorname' => 'American Tonneau',
    'vendorfriendlyname' => 'american-tonneau',
    'vendorshipping' => '0',
  ),
  68 => 
  array (
    'vendorid' => '68',
    'vendorname' => 'Test vendor -r',
    'vendorfriendlyname' => 'test-vendorr',
    'vendorshipping' => '0',
  ),
);

?>